### ISSUE TITLE
Grafico para representar a precipitação

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#10]
Foi feita uma [refatoração no código](https://github.com/Wanhenri/duvida_flask_react/commit/312ac58f191172cb5b763a955fd97093a53556da) onde foi acrescentado as variáveis: 

- precipitation_daily_acu 
- precipitation_daily_max 
- precipitation_daily_min

A próxima etapa é escolher um modelo de gráfico para melhor representar as 3 variáveis em apenas um gráfico. 
Ainda estamos no processo de seleção no [site](https://echarts.apache.org/examples/en/index.html)

**Comment by reisdev** [comment]
Sugestão: EchartLine

**Comment by Wanhenri** [comment]
Na branch [inpe](https://github.com/Wanhenri/duvida_flask_react/tree/inpe) foi criado o componente para representar a [precipitação máxima, mínima e acumulada](https://github.com/Wanhenri/duvida_flask_react/commit/176b9c9718e51f7517781a41be6e9a19a1627cc4). Fazendo uso do [EchartLine](https://github.com/Wanhenri/duvida_flask_react/tree/inpe/app/src/components/Chart/EchartLine)
