### ISSUE TITLE
Problemas com Branchs

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#17]
Foi criado uma Branch chamada **somar** e feito alterações nela. Logo em seguida foi criado uma Branch chamada **inpe** a partir da Branch **somar** .

Elas serão Branch paralelas ou uma irá sobrescrever a outra?

**Comment by reisdev** [comment]
As branchs não interferem entre si. Quando for fazer o merge de uma branch, você pode escolher para qual branch enviá-la! Referência [aqui](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)
