### ISSUE TITLE
Serviços de Cloud e Serviços de Hospedagem

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#21]
Como funciona esses serviços?

Serviços de Cloud:
- AWS;
- Google Cloud; 
- Heroku;
- Digital Ocean; 
- Umbler; 
- entre outros.

Serviços de hospedagem:
- HostGator da vida.

**Comment by reisdev** [comment]
Deploy feito de ambas as aplicações no Heroku.

URLS:
[Front-end](https://duvidaflask-app.herokuapp.com)
[Back-end](https://duvidaflask-api.herokuapp.com)

Referências:

[Deploy React to Heroku](https://dev.to/smithmanny/deploy-your-react-app-to-heroku-2b6f)*
[Deploy Flask to Heroku](https://medium.com/the-andela-way/deploying-a-python-flask-app-to-heroku-41250bda27d0)**

*: Atenção ao comentário sobre buildpack! Essencial
**: Configuração gunicorn deve ser: `web: gunicorn <nome do arquivo python>:<nome do app flask>`
