### ISSUE TITLE
Correção no eixo Y do echartBar

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#3]
Para a construção do echartBar, foi utilizado como exemplo o gráfico disponibilizado no [site](https://echarts.apache.org/examples/en/editor.html?c=dataset-encode0&theme=light). <br />
Feito a aplicação em:
- [echarBar](https://github.com/Wanhenri/duvida_flask_react/blob/master/app/src/components/Chart/EchartBar/index.js) 
- [FetSomar](https://github.com/Wanhenri/duvida_flask_react/blob/master/app/src/components/FetSomar/index.js)

No echartBar apresenta 14 cidades no eixo y, enquanto que no total da API são 27 cidades.

No numero de barras esta correto, somente no numero de labels que não estão corretos.

Não encontrei um campo que apresente uma limitação no eixos Y.

**Comment by reisdev** [comment]
O problema foi corrigido através da configuração do yAxis, no estado graphOption, alterando a seguinte propriedade:

```js
//...
        yAxis: {
          name: this.props.source[0][1],
          axisLabel: {
            interval: 0 // Exibe todos os labels, sem se importar com nada mais
          }
        },
// ...
```
