### ISSUE TITLE
Aplicar a const List (com nomes das cidades) com os codigos das cidades no script FetInpe

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#4]
No [FetInpe](https://github.com/Wanhenri/duvida_flask_react/blob/master/app/src/components/FetInpe/index.js) foi criado uma const chamado List, onde consta o nome de cidades e sua 'UF' correspondente aos códigos fornecidos pela API do INPE.

Não consegui fazer o link entre essa **const List** e os códigos da API.

**Comment by reisdev** [comment]
Modifiquei o objeto para `cityNames`, e construí uma espécie de dicionário ( chave -> valor ), que ficou com o seguinte formato:

```js
// ...
    SBBH: { cidade: "Pampulha", uf: "MG" },
    SBBV: { cidade: "Boa Vista", uf: "RR" },
    SBBR: { cidade: "Juscelino Kubitschek", uf: "DF" },
// ...
```
