### ISSUE TITLE
react weather

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#5]
Atualmente, no script [FetSomar](https://github.com/Wanhenri/duvida_flask_react/blob/master/app/src/components/FetSomar/index.js) estou fazendo uso das libs para icon weather: <br />

- import fontawesome from "@fortawesome/fontawesome";
- import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
- import { faCheckSquare, faCoffee } from "@fortawesome/fontawesome-free-solid"; 

É necessário melhorar a aplicação desses componentes.
[Ainda não implantado]

**Comment by reisdev** [comment]
Para exibir os ícons do FontAwesome é necessário importá-los e exibí-los utilizando o componente `<FontAwesomeIcon>`.

Exemplo:

```jsx
import { faCaretUp } from "@fortawesome/free-solid-svg-icons";
//...
    <FontAwesomeIcon icon={faCaretUp} size="2x" />
//...
```
