### ISSUE TITLE
Datas para os dados Observer

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#9]
Com base no na issue #2 , foi feito uma [refatoração nos códigos](https://github.com/Wanhenri/duvida_flask_react/commit/3934468141eddb6048bb5eb52d646bf1c3540271) e acrescentado o campo **periods**:

```json
  "periods": [
    "2020-01-21 06:00",
    "2020-01-22 06:00",
    "2020-01-23 06:00",
    "2020-01-24 06:00",
    "2020-01-25 06:00",
    "2020-01-26 06:00",
    "2020-01-27 06:00"
  ],
``` 
Ficando com a seguinte caracteristica:

```json
    {
        "city": "RiodeJaneiro-RJ",
        "lat": -22.9,
        "lon": -43.21,
        "day": "2020-01-29",
        "day_obs": [
            "2020-01-28 00:00",
            "2020-01-29 00:00",
            "2020-01-30 00:00",
            "2020-01-31 00:00",
            "2020-02-01 00:00",
            "2020-02-02 00:00",
            "2020-02-03 00:00"
        ],
        "temperature_daily_min": "23.59314727783203",
        "temperature_daily_max": "30.220613479614258",
        "rel_humidity_daily_avg": "68.92266082763672",
        "max_temperature": "28.77445411682129",
        "min_temperature": "22.383502960205078",
        "max_rel_humidity": "86.71380615234375",
        "min_rel_humidity": "49.403987884521484",
        "mean_rel_humidity": "68.05889701843262",
        "metaWeather": "PN"
    },
```

Aplicar em:
- [EchartLine](https://github.com/Wanhenri/duvida_flask_react/tree/master/app/src/components/Chart/EchartLine)
- [FetSomar](https://github.com/Wanhenri/duvida_flask_react/tree/master/app/src/components/FetSomar)

**Comment by Wanhenri** [comment]
Com base no [script feito no repl](https://repl.it/@wanhenri/requestAPI10dias) para visualizar os dados que sai da API, foi identificado que o [script](https://github.com/Wanhenri/duvida_flask_react/blob/master/api/controllers/Somar.py) não esta pegando os dados corretos. Porém, não consegui identificar o que ele esta fazendo de errado.

**Comment by reisdev** [comment]
O problema foi resolvido passando os períodos de forecast e observed na requisição, e utilizando essas datas como o período de cada gráfico.
